export const MenuData = [
    {
        title: 'Home',
        path: '/',
        blockItem: false,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Empresa',
        path: '/empresa',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Produtos',
        path: '/produtos',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Treinamento',
        path: 'http://www.globo.com',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: true,
    },
    {
        title: 'Contato',
        path: '/contato',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Blog',
        path: '/blog',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    }
]