export const MenuData = [
    {
        title: 'Clientes',
        path: '/admin/clientes',
        blockItem: false,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Produtos',
        path: '/admin/produtos',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Distribuidores',
        path: '/admin/providers',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Categorias',
        path: '/admin/categorias',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Blog',
        path: '/admin/blog',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Textos',
        path: '/admin/textos',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: true,
    }
]