export const MenuData = [
    {
        title: 'Clientes',
        path: '/admin/clientes',
        blockItem: false,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Funcionários',
        path: '/admin/funcionarios',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },  
    {
        title: 'Telefone Fixo',
        path: '/admin/phone',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },   
    {
        title: 'Categorias',
        path: '/admin/categorias',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Produtos',
        path: '/admin/produtos',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Produtos Antigos',
        path: '/admin/produtos-antigos',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Distribuidores',
        path: '/admin/providers',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Catálogos',
        path: '/admin/catalogs',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Blog',
        path: '/admin/blog',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Textos',
        path: '/admin/textos',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Carrossel',
        path: '/admin/carrossel',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Redes Sociais',
        path: '/admin/redes-sociais',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: false,
    },
    {
        title: 'Firebase',
        path: 'https://console.firebase.google.com/project/jmtell/overview',
        blockItem: true,
        iconClosed: null,
        iconOpened: null,
        externalLink: true,
    }
]